name: skinaware_flutter
description: A new Flutter project with Serverpod.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.8.0'
  flutter: '^3.32.0'

dependencies:

  audio_waveforms: ^2.0.1
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.1.0
  flutter_screenutil: ^5.9.3
  skinaware_client:
    path: ../skinaware_client
  http: ^1.6.0
  lottie: ^3.3.2
  lucide_icons: ^0.257.0
  serverpod_auth_idp_flutter: 3.2.2
  serverpod_flutter: 3.2.2
  shimmer: ^3.0.0
  wave_blob: ^1.0.5
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  shared_preferences: ^2.5.4
  google_sign_in: ^7.2.0
  pytorch_lite: ^1.0.0
  image_picker: ^1.0.7
  image: ^4.0.17

dev_dependencies:
  flutter_lints: '>=3.0.0 <7.0.0'
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/animations/
    - assets/illustrations/
    - assets/icons/
    - assets/models/


  fonts:

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf

    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway/Raleway-Regular.ttf
        - asset: assets/fonts/raleway/Raleway-Medium.ttf
          weight: 300
        - asset: assets/fonts/raleway/Raleway-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/raleway/Raleway-Bold.ttf
          weight: 700
dependency_overrides:
  flutter_secure_storage: ^10.0.0

