name: skinaware_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '^3.8.0'

dependencies:
  serverpod: ^3.2.2
  serverpod_auth: ^3.2.2
  serverpod_auth_idp_server: ^3.2.2
  serverpod_auth_idp_client: ^3.2.2
  serverpod_auth_core: ^3.2.2
  serverpod_auth_core_server: ^3.2.2
  serverpod_auth_core_client: ^3.2.2


dev_dependencies:
  lints: '>=3.0.0 <7.0.0'
  serverpod_test: 3.1.1
  test: ^1.25.5


serverpod:
  scripts:
 
    start: dart bin/main.dart --apply-migrations


    flutter_build: cd ../skinaware_flutter && flutter build web --base-href /app/ --wasm && rm -rf ../skinaware_server/web/app && mv build/web/ ../skinaware_server/web/app
