
apiServer:
  port: 8080
  publicHost: localhost
  publicPort: 8080
  publicScheme: http


insightsServer:
  port: 8081
  publicHost: localhost
  publicPort: 8081
  publicScheme: http


webServer:
  port: 8082
  publicHost: localhost
  publicPort: 8082
  publicScheme: http


database:
  host: skinaware-klassicmak-1668.h.aivencloud.com
  port: 23192
  name: epidexa
  password: AVNS_yufajU5z0j0F0LVsTQT
  user: avnadmin
  requireSsl: true
  maxConnections: 2


sessionLogs:
  persistentEnabled: true
  consoleEnabled: true
  consoleLogFormat: text # Defaults to "json", options are "text" or "json"

