
apiServer:
  port: 8080
  publicHost: localhost
  publicPort: 8080
  publicScheme: http


insightsServer:
  port: 8081
  publicHost: localhost
  publicPort: 8081
  publicScheme: http


webServer:
  port: 8082
  publicHost: localhost
  publicPort: 8082
  publicScheme: http


database:
  host: aws-1-eu-west-1.pooler.supabase.com
  port: 6543
  name: postgres
  user: postgres.hklbaolpqmddlgjptity
  password: CybcJ1oU2CwXby3a
  requireSsl: true


sessionLogs:
  persistentEnabled: true
  consoleEnabled: true
  consoleLogFormat: text # Defaults to "json", options are "text" or "json"

