
apiServer:
  port: 8080
  publicHost: https://epidexa-498245313775.us-central1.run.app
  publicPort: 8080
  publicScheme: https


database:
  host: ep-snowy-sun-ahssim1d-pooler.c-3.us-east-1.aws.neon.tech
  port: 5432
  name: neondb
  password: npg_ixTzNGg3qXJ0
  user: neondb_owner
  requireSsl: true
  maxConnectionCount: 10


sessionLogs:
  persistentEnabled: true
  consoleEnabled: true
  consoleLogFormat: text 

