
apiServer:
  port: 8080
  publicHost: https://epidexa-498245313775.us-central1.run.app
  publicPort: 8080
  publicScheme: https


database:
  host: skinaware-klassicmak-1668.h.aivencloud.com
  port: 23192
  name: defaultdb
  password: AVNS_yufajU5z0j0F0LVsTQT
  user: avnadmin
  requireSsl: true
  maxConnectionCount: 10


sessionLogs:
  persistentEnabled: true
  consoleEnabled: true
  consoleLogFormat: text 

